### ISSUE TITLE
Conflicting key bindings with evil-org

### ISSUE THREAD

**Issue by rolag** [itai33/evil-tex#8]
Thanks for the great package. Org-mode supports LaTeX too so it makes sense to enable this in org-mode, but org-mode and [evil-org](https://github.com/Somelauw/evil-org-mode) has some conflicting key bindings with this package: `[[`, `]]`, `vie` and `vae`.

The evil-tex `[[` and `]]` don't really make sense in org-mode so the org-mode ones can take priority in org-mode.

In evil-org `vie` and `vae` mean the surrounding org-mode element, like a table cell or entire code block, while in evil-tex they mean the LaTeX environment block. I think it makes sense to use the evil-tex functions when in a LaTeX environment and fallback to the the evil-org functions otherwise.

I have the following workaround in my init.el but it would be nice to have this resolved upstream. Would you consider a pull request for this here?

```elisp
      (evil-define-text-object evil-tex-inner-env-or-evil-org-inner-object (count &optional beg end type)
        "Default to `evil-tex-inner-env' and fallback on `evil-org-inner-object'."
        (condition-case nil (evil-tex-inner-env count beg end type)
          (error (when (eq major-mode 'org-mode)
                   (evil-org-inner-object count beg end type)))))
      (evil-define-text-object evil-tex-an-env-or-evil-org-an-object (count &optional beg end type)
        "Default to `evil-tex-an-env' and fallback on `evil-org-an-object'."
        (condition-case nil (evil-tex-an-env count beg end type)
          (error (when (eq major-mode 'org-mode)
                   (evil-org-an-object count beg end type)))))
      (defun evil-tex-go-back-section-or-org-previous-visible-heading (&optional arg)
        (interactive)
        (if (eq major-mode 'org-mode)
            (org-previous-visible-heading (or arg 1))
          (evil-tex-go-back-section arg)))
      (defun evil-tex-go-forward-section-or-org-next-visible-heading (&optional arg)
        (interactive)
        (if (eq major-mode 'org-mode)
            (org-next-visible-heading (or arg 1))
          (evil-tex-go-forward-section arg)))
      (defun setup-evil-tex-binding-replacements ()
        (evil-define-key* '(normal motion) evil-tex-mode-map
          [remap evil-tex-go-back-section] 'evil-tex-go-back-section-or-org-previous-visible-heading
          [remap evil-tex-go-forward-section] 'evil-tex-go-forward-section-or-org-next-visible-heading)
        (evil-define-key '(visual operator) 'evil-tex-mode-map
          [remap evil-tex-inner-env] 'evil-tex-inner-env-or-evil-org-inner-object
          [remap evil-tex-an-env] 'evil-tex-an-env-or-evil-org-an-object))
      (add-hook 'evil-tex-mode-hook 'setup-evil-tex-binding-replacements nil 'local)
```

**Comment by ymarco** [comment]
> Would you consider a pull request for this here?

We would, but I'm reluctant about adding dependencies on org and evil-org. 
I think if `major-mode` is `org-mode` then we can safely assume that org functions are loaded without listing `org` as a dependency, but what about evil-org?

**Comment by rolag** [comment]
We could have a check like:
```elisp
(condition-case nil (evil-tex-an-env)
  (error (when (and (eq major-mode 'org-mode) (fboundp 'evil-org-an-object))
           (evil-org-an-object)))
```

This would avoid placing an explicit dependency on evil-org.

**Comment by ymarco** [comment]
All right, go for it :)

**Comment by ymarco** [comment]
Note: from experiance in laas, checking (derived-mode-p 'org-mode) is better than (eq major-mode 'org-mode), as people wanna use derived modes such as org-journal.
